=head1 NAME 

Webservice::WaitList

=head1 VERSION

0.01

=head1 DESCRIPTION

A backend for an application that shows restaurants near you (within X miles) and their respective wait times if you wanted to eat *right now*.

=head1 SYNOPSIS

 #!/usr/bin/env perl

 use strict;
 use warnings;

 use feature qw(say);
 use Webservice::WaitList;

 my $app = Webservice::WaitList->new;
 my $charlottesville = '38.034667,-78.481145';
 foreach my $restaurant ( $app->restaurants_near_me($charlottesville) ) {
    say $restaurant;
 }
